# Generated by Django 5.1.6 on 2025-02-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book'), ('can_view', 'Can view book')]},
        ),
    ]
